Bugfix/compilation error with new esp idf
espressif/esp-idf-cxx pull request #7
Opened 2022-08-30 10:13 UTC by SoucheSouche

Fix compilation error related to the change in es-idf driver APIs.

2022-08-30 10:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/espressif/esp-idf-cxx?pullRequest=7) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/espressif/esp-idf-cxx?pullRequest=7) before we can accept your contribution.<br/><hr/>**Guillaume Souchere** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/espressif/esp-idf-cxx?pullRequest=7) it.</sub>

2022-09-05 08:00 UTC, 0xjakob requested changes
@SoucheSouche Thanks a lot for fixing the compile errors!

If have just a little change request. The rest of the code looks good to me!

2022-09-05 08:09 UTC, SoucheSouche commented on test_apps/include/utils_cxx.hpp
> +#define APP_TESTS_LOG(fmt, ...) esp_log_write(ESP_LOG_INFO, APP_TESTS_TAG, LOG_FORMAT(I, fmt), esp_log_timestamp(), APP_TESTS_TAG, ##__VA_ARGS__)
I changed the naming to fit the directory name as suggested.

2022-09-05 08:30 UTC, 0xjakob approved these changes

2022-09-05 08:34 UTC, merged